DoctorsOffice/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace DoctorsOffice.Models
{
  public class DoctorsOfficeContextFactory : IDesignTimeDbContextFactory<DoctorsOfficeContext>
  {
    DoctorsOfficeContext IDesignTimeDbContextFactory<DoctorsOfficeContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<DoctorsOfficeContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new DoctorsOfficeContext(builder.Options);
    }
  }
}

DoctorsOffice/Models/Doctor.cs
using System.Collections.Generic;

namespace DoctorsOffice.Models
{
  public class Doctor
  {
    public Doctor()
    {
      this.Patients = new HashSet<DoctorPatient>();
    }
    public int DoctorId {get; set;}
    public string Name {get; set;}
    public string Specialty {get; set;}
    public virtual ICollection<DoctorPatient> Patients { get; set;}
  }
}

DoctorsOffice/Models/DoctorPatient.cs
namespace DoctorsOffice.Models
{
  public class DoctorPatient
  {
    public int DoctorPatientId {get; set;} 
    public int DoctorId {get; set;}
    public int PatientId {get; set;}
    public Doctor Doctor {get; set;}
    public Patient Patient {get; set;}

  }
}

DoctorsOffice/Models/DoctorsOfficeContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DoctorsOffice.Models
{
  public class DoctorsOfficeContext : DbContext
  {
    public virtual DbSet<Doctor> Doctors {get; set;}
    public virtual DbSet<Patient> Patients {get; set;}
    public DbSet<DoctorPatient> DoctorPatient {get; set;}
    public DoctorsOfficeContext(DbContextOptions options): base(options) {}
  }
}

DoctorsOffice/Models/Patient.cs
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoctorsOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.Doctors = new HashSet<DoctorPatient>();
    }
    public int PatientId { get; set; }
    public string Name  { get; set; }
    public string Affliction  { get; set; }
    public virtual ICollection<DoctorPatient> Doctors { get; set; }
  }
}

DoctorsOffice/Models/Speciality.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Systems;

namespace DoctorsOffice.Models
{
  public class Speciality
  {
    public Speciality()
    {
      this.Doctors = new HashSet<DoctorSpeciality>();
    }
    public int SpecialityId { get; set; }
    public string Type  { get; set; }
    public ICollection<DoctorSpeciality> Doctors { get; }
  }
}

DoctorsOffice/Models/Specialty.cs
// using System.Collections.Generic;
// using System.ComponentModel.DataAnnotations.Schema;
// using System;

// namespace DoctorsOffice.Models
// {
//   public class Specialty
//   {
//     public Specialty()
//     {
//       this.Doctors = new HashSet<DoctorSpecialty>();
//     }
//     public int SpecialtyId { get; set; }
//     public string Type  { get; set; }
//     public ICollection<DoctorSpecialty> Doctors { get; }
//   }
// }

DoctorsOffice/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorsOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace DoctorsOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DoctorsOfficeContext _db;

    public DoctorsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
          .Include(doctor => doctor.Patients)
          .ThenInclude(join => join.Patient)
          .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = doctor.DoctorId });
    }

    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DoctorsOffice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DoctorsOffice.Controllers
{
    public class HomeController : Controller
    {
      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }
    }
}

DoctorsOffice/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using DoctorsOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace DoctorsOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorsOfficeContext _db;
    public PatientsController(DoctorsOfficeContext db)
    {
      _db = db;
    }
    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
          .Include(patient => patient.Doctors)
          .ThenInclude(join => join.Doctor)
          .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }
    public ActionResult Create()
    {
    ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
    return View();
    }
    public ActionResult Edit(int id)
    {
    var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
    ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
    return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      var testVariable = _db.DoctorPatient.FirstOrDefault(join => join.PatientId == patient.PatientId && join.DoctorId == DoctorId);

      if(testVariable != null)
      {
        _db.Entry(patient).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = patient.PatientId});
      }
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = patient.PatientId});
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
    if (DoctorId != 0)
    {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
    }
    _db.SaveChanges();
    return RedirectToAction("Index");
    }
    public ActionResult Index()
    {
      List<Patient> model = _db.Patients.ToList();
      return View(model);
    }
  }
}

DoctorsOffice/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h1>Add New Doctors</h1>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)<br>

    @Html.LabelFor(model => model.Specialty)
    @Html.TextBoxFor(model => model.Specialty)

    <input type="submit" value="Add new doctor" class="btn btn-outline-dark" />
}
<hr>
<input type="button" value="Doctors List" onclick="location.href='@Url.Action("Index", "Docotrs")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Doctors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Are you sure you want to delete this doctor?</h2>

<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
<p>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete"/>
}
<hr>
<input type="button" value="Doctor List" onclick="location.href='@Url.Action("Index", "Doctor")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Doctor Details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.Name)</h3>
<h5>Dr. of @Html.DisplayFor(model => model.Specialty)</h5>

@if(@Model.Patients.Count() == 0)
{
  <p>This doctor has no patients assigned to them yet.</p>
}
else
{
  <div class="well">
      <h4 class="col-sm-3">Current Patients:</h4>
      <ul>
      @foreach(var join in Model.Patients)
      {
        <li class="col-sm-9">@Html.ActionLink(@join.Patient.Name, "Details", "Patients", new { id = @join.Patient.PatientId})</li>
      }
      </ul>
  </div>
}
<hr>
<input type="button" value="Add Patient to this Doc" onclick="location.href='@Url.Action("Create", "Patients", new { id = Model.DoctorId })';" class="btn btn-outline-primary" />
<input type="button" value="Edit Doctor" onclick="location.href='@Url.Action("Edit", "Doctors", new { id = Model.DoctorId })';" class="btn btn-primary" />
<input type="button" value="Delete Doctor" onclick="location.href='@Url.Action("Delete", "Doctors", new { id = Model.DoctorId })';" class="btn btn-primary" />
<input type="button" value="Doctor List" onclick="location.href='@Url.Action("Index", "Doctors")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h1>Edit this Doctor</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.DoctorId)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)<br>

    @Html.LabelFor(model => model.Specialty)
    @Html.EditorFor(model => model.Specialty)

    <input type="submit" value="Update Doctor" class="btn btn-outline-dark" />
}
<hr>
<input type="button" value="Doctors List" onclick="location.href='@Url.Action("Index", "Doctors")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Doctor>;

<h1>Doctors</h1>

@if (@Model.Count == 0)
{
  <h3>No doctors have been added yet!</h3>
} 

@foreach (Doctor doctor in Model)
{
  <li>@Html.ActionLink($"{doctor.Name}", "Details", new { id = doctor.DoctorId }) || Dr. of @doctor.Specialty</li>
}
<hr>
<input type="button" value="Add new doctor" onclick="location.href='@Url.Action("Create", "Doctors")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<h1>Doctor's Office</h1>
<br>
<input type="button" value="Doctor's List" onclick="location.href='@Url.Action("Index", "Doctors")';" class="btn btn-primary" />
<br><br>
@* <input type="button" value="Specialties List" onclick="location.href='@Url.Action("Index", "Specialties")';" class="btn btn-primary" />
<br><br> *@
<input type="button" value="Patient List" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Add a Doctor</h2>

<h4>Add a doctor to this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PatientId)

    @Html.Label("Select Doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Save" />
}
<hr>
<input type="button" value="Patient List" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h4>Add a new Patient</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Affliction)
    @Html.TextBoxFor(model => model.Affliction)
    <br>
    @Html.Label("Select doctor")
    @Html.DropDownList("DoctorId")
    <br>
  <input type="submit" value="Add new patient" class="btn btn-outline-dark" />
}
<hr>
<input type="button" value="Patient List" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<hr>
<input type="button" value="Patient List" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Patient Details</h2>
<hr />
<h3>Name: @Html.DisplayFor(model => model.Name)</h3>
<h3>Afflictions: @Html.DisplayFor(model => model.Affliction)</h3>


@if(@Model.Doctors.Count == 0)
{
  <p>This patient is not seeing any doctors</p>
}
else
{
  <h4>Doctors the patient belongs to:</h4>
  <ul>
  @foreach(var join in Model.Doctors)
  {
    <li>@Html.ActionLink(@join.Doctor.Name, "Details", "Doctors", new { id = @join.Doctor.DoctorId})</li>
    @using (Html.BeginForm("DeleteDoctor", "Patients"))
    {
      @Html.Hidden("joinId", @join.DoctorPatientId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}
<hr>
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />
<input type="button" value="Edit Patient" onclick="location.href='@Url.Action("Edit", "Patients", new { id = Model.PatientId })';" class="btn btn-primary" />
<input type="button" value="Delete Patient" onclick="location.href='@Url.Action("Delete", "Patients", new { id = Model.PatientId })';" class="btn btn-primary" />
@* <input type="button" value="Add a Doctor" onclick="location.href='@Url.Action("AddDoctor", "Patients", new { id = Model.PatientId })';" class="btn btn-primary" /> *@
<input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Edit</h2>

<h4>Edit this Patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PatientId)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Affliction)
    @Html.EditorFor(model => model.Affliction)
    <br>
    @Html.Label("Select doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Save" />
}
<hr>
<input type="button" value="Patient List" onclick="location.href='@Url.Action("Index", "Patients")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Patient>;

<h1>Patients</h1>

@if (@Model.Count == 0)
{
  <h3>No patients have been added yet!</h3>
} 

@foreach (Patient patient in Model)
{
  <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId })</li>
}
<hr>
<input type="button" value="Add Patient" onclick="location.href='@Url.Action("Create", "Patients")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

DoctorsOffice/Views/Shared/Footer.cshtml
<p>Doctors without Patients. Est 2020</p>

DoctorsOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Doctor's Office</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'>
    <link href="https://fonts.googleapis.com/css2?family=Antic+Slab&family=Quicksand&family=Recursive:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <br>
    <br>
    <br>
    <div class="container">
      @RenderBody()
      <br>
      @Html.Partial("Footer")
    </div>
  </body>
</html>

DoctorsOffice/Views/Specialties/Index.cshtml
@* @{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Specialty>;

<h1>Specialties</h1>

@if (@Model.Count == 0)
{
  <h3>No doctors have been added yet!</h3>
} 

@foreach (Specialty specialty in Model)
{
  <li>@Html.ActionLink($"{specialty.Type}", "Details", new { id = specialty.SpecialtyId })</li>
}
<hr>
<input type="button" value="Add new doctor" onclick="location.href='@Url.Action("Create", "Doctors")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" /> *@